2025-01-17 22:24:16,070 - error_logger - ERROR - Unexpected error: [Errno -3] Temporary failure in name resolution
2025-01-17 22:32:31,748 - error_logger - ERROR - Unexpected error: [Errno -3] Temporary failure in name resolution
2025-01-18 00:31:24,765 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x785895243bd0>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 00:34:31,326 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x719cb6312010>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 00:34:58,938 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x704f2e5954d0>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 00:37:31,614 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x743d4f82dad0>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 00:37:51,286 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x7c930ec99410>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 00:39:18,496 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x70375ef81890>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 00:40:54,223 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x73baf9195390>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:31:00,486 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x7d746e99e590>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:32:21,591 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x73cb69ddf390>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:34:18,179 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x789bc20a5fd0>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:34:20,947 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x789bc20a5ed0>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:39:13,624 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x71e0ca0a9e50>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:41:25,623 - error_logger - ERROR - Validation error: 1 validation error for Application
  Input should be a valid dictionary or instance of Application [type=model_type, input_value=<models.Application object at 0x7eba3f39ded0>, input_type=Application]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
2025-01-18 13:43:22,378 - error_logger - ERROR - Failed to send application to Kafka: 26. Error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:43:22,378 - error_logger - ERROR - Kafka error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:43:43,702 - error_logger - ERROR - Failed to send application to Kafka: 27. Error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:43:43,702 - error_logger - ERROR - Kafka error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:46:56,721 - error_logger - ERROR - Failed to send application to Kafka: 28. Error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:46:56,721 - error_logger - ERROR - Kafka error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:50:35,340 - error_logger - ERROR - Failed to send application to Kafka: 29. Error: KafkaConnectionError: No connection to node with id 1001
2025-01-18 13:50:35,340 - error_logger - ERROR - Kafka error: KafkaConnectionError: No connection to node with id 1001
2025-01-18 13:52:35,856 - error_logger - ERROR - Failed to send application to Kafka: 1. Error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 13:52:35,856 - error_logger - ERROR - Kafka error: KafkaConnectionError: Unable to bootstrap from [('kafka', 9092, <AddressFamily.AF_UNSPEC: 0>)]
2025-01-18 14:00:37,691 - error_logger - ERROR - Failed to send application to Kafka: 2. Error: KafkaConnectionError: No connection to node with id 1001
2025-01-18 14:00:37,691 - error_logger - ERROR - Kafka error: KafkaConnectionError: No connection to node with id 1001
2025-01-18 19:00:21,614 - error_logger - ERROR - Unexpected error: [Errno -3] Temporary failure in name resolution
